# Generated by Django 2.1.8 on 2020-01-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiXinFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('document', 'document')], default='image', max_length=10)),
                ('file', models.FileField(upload_to='weixinFiles')),
            ],
        ),
    ]
